# Generated by Django 5.2.7 on 2025-12-11 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageapp', '0004_alter_image_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('watermark_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('metadata', models.TextField()),
                ('file_hash', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=255)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='reports/originals/')),
                ('tampered_image', models.ImageField(blank=True, null=True, upload_to='reports/tampered/')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='reports/heatmap/')),
                ('pdf', models.FileField(null=True, upload_to='reports/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='imageapp.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
