# Generated by Django 5.2.7 on 2025-12-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdf/'),
        ),
    ]
