# Generated by Django 5.2.7 on 2025-12-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_alter_report_pdf'),
        ('watermark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comparison_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='suspicious_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/suspicious/'),
        ),
        migrations.AddField(
            model_name='report',
            name='suspicious_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='watermark_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watermark.watermarkrecord'),
        ),
    ]
