# Generated by Django 5.2.7 on 2025-12-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_add_suspicious_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comparison_stats',
        ),
    ]
