# Generated by Django 5.2.7 on 2025-12-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_remove_report_comparison_stats'),
        ('watermark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='watermark_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='watermark.watermarkrecord'),
        ),
    ]
