# Generated by Django 5.2.7 on 2025-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='batch_group',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='batch_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
