# Generated by Django 5.2.7 on 2025-12-10 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_image_batch_group_image_batch_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='batch_group',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='imageapp.batch'),
        ),
    ]
