# Generated by Django 5.2.7 on 2025-12-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_alter_image_options_remove_image_batch_group_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageapp.batch'),
        ),
    ]
