# Generated by Django 5.2.7 on 2025-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0004_alter_image_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
