# Generated by Django 5.2.7 on 2025-12-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageapp', '0005_image_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermarked_image', models.ImageField(upload_to='watermarked/')),
                ('perceptual_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_hash', models.BinaryField()),
                ('aes_key_encrypted', models.BinaryField()),
                ('aes_iv_encrypted', models.BinaryField()),
                ('correlation_score', models.FloatField(blank=True, null=True)),
                ('phash_distance', models.IntegerField(blank=True, null=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='imageapp.image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
